# Generated by Django 5.1.3 on 2025-09-20 09:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='report',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.AddField(
            model_name='complaint',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('organic', 'Organic'), ('metal', 'Metal'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
